import type { RegistryEntry } from "./types.ts";

/**
 * Curated registry of notable open-weight models.
 *
 * Sizes are Q4_K_M from ollama.com/library/<model> (the default quant).
 * Benchmarks from official READMEs / release blogs.
 * Updated by hand as new models come out.
 */
export const REGISTRY: RegistryEntry[] = [
  //━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  //  AGENTIC CODING — purpose-built for tool use, SWE tasks
  //━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  {
    repoId: "Qwen/Qwen3-Coder-Next-80B-A3B",
    name: "Qwen3-Coder-Next",
    hfUrl: "https://huggingface.co/Qwen/Qwen3-Coder-Next-80B-A3B",
    sizeGb: 52,
    paramsTotal: "80B",
    paramsActive: "3B",
    context: "256K",
    architecture: "moe",
    category: "coding",
    tags: ["tools"],
    benchmarks: {},
    note: "Biggest agentic coder. 80B MoE, 3B active. Tight fit at 52 GB.",
  },
  {
    repoId: "Qwen/Qwen3.6-35B-A3B",
    name: "Qwen3.6:35b",
    hfUrl: "https://huggingface.co/Qwen/Qwen3.6-35B-A3B",
    sizeGb: 24,
    paramsTotal: "35B",
    paramsActive: "3B",
    context: "256K",
    architecture: "moe",
    category: "coding",
    tags: ["tools", "thinking", "vision"],
    benchmarks: { sweBenchVerified: 73.4, terminalBench: 51.5 },
    note: "Best SWE-bench that fits. Vision. Thinking preservation across turns.",
  },
  {
    repoId: "Qwen/Qwen3.6-27B-A3B",
    name: "Qwen3.6:27b",
    hfUrl: "https://huggingface.co/Qwen/Qwen3.6-27B-A3B",
    sizeGb: 17,
    paramsTotal: "27B",
    paramsActive: "3B",
    context: "256K",
    architecture: "moe",
    category: "coding",
    tags: ["tools", "thinking", "vision"],
    benchmarks: {},
    note: "Smaller Qwen3.6 sibling. Nearly as capable, 17 GB.",
  },
  {
    repoId: "poolside/Laguna-XS-2.1",
    name: "Laguna XS 2.1",
    hfUrl: "https://huggingface.co/poolside/Laguna-XS-2.1",
    sizeGb: 20,
    paramsTotal: "33B",
    paramsActive: "3B",
    context: "256K",
    architecture: "moe",
    category: "coding",
    tags: ["tools", "thinking"],
    benchmarks: { sweBenchVerified: 70.9, terminalBench: 37.5 },
    note: "Fastest. FP8 KV cache. Purpose-built for agentic coding.",
  },
  {
    repoId: "Qwen/Qwen3-Coder-30B-A3B",
    name: "Qwen3-Coder:30b",
    hfUrl: "https://huggingface.co/Qwen/Qwen3-Coder-30B-A3B",
    sizeGb: 19,
    paramsTotal: "30B",
    paramsActive: "3.3B",
    context: "256K",
    architecture: "moe",
    category: "coding",
    tags: ["tools"],
    benchmarks: {},
    note: "1M context with YaRN. Light, purpose-built coder.",
  },
  {
    repoId: "deepseek-ai/DeepSeek-Coder-V2-Lite-Instruct",
    name: "DeepSeek-Coder-V2-Lite",
    hfUrl: "https://huggingface.co/deepseek-ai/DeepSeek-Coder-V2-Lite-Instruct",
    sizeGb: 9,
    paramsTotal: "16B",
    paramsActive: null,
    context: "128K",
    architecture: "dense",
    category: "coding",
    tags: ["tools"],
    benchmarks: {},
    note: "DeepSeek's code model. 128K context, light.",
  },
  {
    repoId: "mistralai/Codestral-22B",
    name: "Codestral:22b",
    hfUrl: "https://huggingface.co/mistralai/Codestral-22B",
    sizeGb: 13,
    paramsTotal: "22B",
    paramsActive: null,
    context: "32K",
    architecture: "dense",
    category: "coding",
    tags: [],
    benchmarks: {},
    note: "Mistral's code model. Dense 22B. Fill-in-the-middle trained.",
  },
  {
    repoId: "Qwen/Qwen2.5-Coder-32B-Instruct",
    name: "Qwen2.5-Coder:32b",
    hfUrl: "https://huggingface.co/Qwen/Qwen2.5-Coder-32B-Instruct",
    sizeGb: 19,
    paramsTotal: "32B",
    paramsActive: null,
    context: "32K",
    architecture: "dense",
    category: "coding",
    tags: [],
    benchmarks: {},
    note: "Older but solid. Dense 32B coder. Cheap at Q4.",
  },
  {
    repoId: "Qwen/Qwen2.5-Coder-14B-Instruct",
    name: "Qwen2.5-Coder:14b",
    hfUrl: "https://huggingface.co/Qwen/Qwen2.5-Coder-14B-Instruct",
    sizeGb: 9,
    paramsTotal: "14B",
    paramsActive: null,
    context: "32K",
    architecture: "dense",
    category: "coding",
    tags: [],
    benchmarks: {},
    note: "Light dense coder. Fits anywhere.",
  },
  {
    repoId: "mistralai/Devstral-24B",
    name: "Devstral:24b",
    hfUrl: "https://huggingface.co/mistralai/Devstral-24B",
    sizeGb: 14,
    paramsTotal: "24B",
    paramsActive: null,
    context: "128K",
    architecture: "dense",
    category: "coding",
    tags: ["tools"],
    benchmarks: { sweBenchVerified: 46.8 },
    note: "Apache 2.0. Lightest agentic coder. Mistral + All Hands AI.",
  },

  //━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  //  GENERAL — strong all-rounders, good reasoning & tool use
  //━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  {
    repoId: "google/gemma-4-31b-it",
    name: "Gemma4:31b",
    hfUrl: "https://huggingface.co/google/gemma-4-31b-it",
    sizeGb: 20,
    paramsTotal: "31B",
    paramsActive: null,
    context: "256K",
    architecture: "dense",
    category: "general",
    tags: ["tools", "thinking", "vision"],
    benchmarks: { liveCodeBench: 80.0, mmluPro: 85.2 },
    note: "Best reasoning+dense. LiveCodeBench 80%. Vision.",
  },
  {
    repoId: "google/gemma-4-26b-it",
    name: "Gemma4:26b",
    hfUrl: "https://huggingface.co/google/gemma-4-26b-it",
    sizeGb: 18,
    paramsTotal: "26B",
    paramsActive: "3.8B",
    context: "256K",
    architecture: "moe",
    category: "general",
    tags: ["tools", "thinking", "vision"],
    benchmarks: { liveCodeBench: 77.1, mmluPro: 82.6 },
    note: "MoE Gemma4. Faster than 31b, slightly weaker.",
  },
  {
    repoId: "google/gemma-4-12b-it",
    name: "Gemma4:12b",
    hfUrl: "https://huggingface.co/google/gemma-4-12b-it",
    sizeGb: 7.6,
    paramsTotal: "12B",
    paramsActive: null,
    context: "256K",
    architecture: "dense",
    category: "general",
    tags: ["tools", "thinking", "vision"],
    benchmarks: {},
    note: "Lightest Gemma4. 256K context. Vision. Good for laptops.",
  },
  {
    repoId: "meta-llama/Llama-3.3-70B-Instruct",
    name: "Llama 3.3 70B",
    hfUrl: "https://huggingface.co/meta-llama/Llama-3.3-70B-Instruct",
    sizeGb: 43,
    paramsTotal: "70B",
    paramsActive: null,
    context: "128K",
    architecture: "dense",
    category: "general",
    tags: ["tools"],
    benchmarks: {},
    note: "Most ecosystem support. Dense 70B = slow on CPU. Battle-tested.",
  },
  {
    repoId: "meta-llama/Llama-3.1-8B-Instruct",
    name: "Llama 3.1 8B",
    hfUrl: "https://huggingface.co/meta-llama/Llama-3.1-8B-Instruct",
    sizeGb: 4.7,
    paramsTotal: "8B",
    paramsActive: null,
    context: "128K",
    architecture: "dense",
    category: "general",
    tags: ["tools"],
    benchmarks: {},
    note: "Universal baseline. Fits anywhere. Good for quick tasks.",
  },
  {
    repoId: "microsoft/Phi-4-mini-instruct",
    name: "Phi-4:14b",
    hfUrl: "https://huggingface.co/microsoft/Phi-4-mini-instruct",
    sizeGb: 9,
    paramsTotal: "14B",
    paramsActive: null,
    context: "16K",
    architecture: "dense",
    category: "general",
    tags: [],
    benchmarks: {},
    note: "Microsoft's small model. Punchy for its size.",
  },
  {
    repoId: "mistralai/Mistral-Small-3.2-24B",
    name: "Mistral Small 3.2:24b",
    hfUrl: "https://huggingface.co/mistralai/Mistral-Small-3.2-24B",
    sizeGb: 15,
    paramsTotal: "24B",
    paramsActive: null,
    context: "128K",
    architecture: "dense",
    category: "general",
    tags: ["tools", "vision"],
    benchmarks: {},
    note: "Latest Mistral small. Improved function calling. Vision.",
  },
  {
    repoId: "mistralai/Mistral-Small-3.1-24B",
    name: "Mistral Small 3.1:24b",
    hfUrl: "https://huggingface.co/mistralai/Mistral-Small-3.1-24B",
    sizeGb: 15,
    paramsTotal: "24B",
    paramsActive: null,
    context: "128K",
    architecture: "dense",
    category: "general",
    tags: ["tools", "vision"],
    benchmarks: {},
    note: "Previous Mistral small. Solid, well-tested.",
  },
  {
    repoId: "mistralai/Mistral-Nemo-Instruct-2407",
    name: "Mistral Nemo:12b",
    hfUrl: "https://huggingface.co/mistralai/Mistral-Nemo-Instruct-2407",
    sizeGb: 7.5,
    paramsTotal: "12B",
    paramsActive: null,
    context: "128K",
    architecture: "dense",
    category: "general",
    tags: [],
    benchmarks: {},
    note: "Apache 2.0. 128K context. Good multilingual.",
  },
  {
    repoId: "Qwen/Qwen3-30B-A3B",
    name: "Qwen3:30b",
    hfUrl: "https://huggingface.co/Qwen/Qwen3-30B-A3B",
    sizeGb: 19,
    paramsTotal: "30B",
    paramsActive: "3B",
    context: "256K",
    architecture: "moe",
    category: "general",
    tags: ["tools", "thinking"],
    benchmarks: {},
    note: "Original Qwen3 MoE. Solid all-rounder with thinking.",
  },
  {
    repoId: "Qwen/Qwen3-32B",
    name: "Qwen3:32b",
    hfUrl: "https://huggingface.co/Qwen/Qwen3-32B",
    sizeGb: 20,
    paramsTotal: "32B",
    paramsActive: null,
    context: "40K",
    architecture: "dense",
    category: "general",
    tags: ["tools", "thinking"],
    benchmarks: {},
    note: "Dense Qwen3. Less memory efficient than MoE variant.",
  },
  {
    repoId: "Qwen/Qwen2.5-72B-Instruct",
    name: "Qwen2.5:72b",
    hfUrl: "https://huggingface.co/Qwen/Qwen2.5-72B-Instruct",
    sizeGb: 42,
    paramsTotal: "72B",
    paramsActive: null,
    context: "32K",
    architecture: "dense",
    category: "general",
    tags: [],
    benchmarks: {},
    note: "Old but capable. Dense 72B = slow. Needs 43 GB.",
  },
  {
    repoId: "Qwen/Qwen2.5-32B-Instruct",
    name: "Qwen2.5:32b",
    hfUrl: "https://huggingface.co/Qwen/Qwen2.5-32B-Instruct",
    sizeGb: 20,
    paramsTotal: "32B",
    paramsActive: null,
    context: "32K",
    architecture: "dense",
    category: "general",
    tags: [],
    benchmarks: {},
    note: "Dense 32B. Balanced size/quality.",
  },
  {
    repoId: "NousResearch/Hermes-3-Llama-3.1-70B",
    name: "Hermes3:70b",
    hfUrl: "https://huggingface.co/NousResearch/Hermes-3-Llama-3.1-70B",
    sizeGb: 40,
    paramsTotal: "70B",
    paramsActive: null,
    context: "128K",
    architecture: "dense",
    category: "general",
    tags: ["tools"],
    benchmarks: {},
    note: "Best tool-calling fine-tune. Old (Llama 3.1 base).",
  },
  {
    repoId: "NousResearch/Hermes-3-Llama-3.1-8B",
    name: "Hermes3:8b",
    hfUrl: "https://huggingface.co/NousResearch/Hermes-3-Llama-3.1-8B",
    sizeGb: 4.7,
    paramsTotal: "8B",
    paramsActive: null,
    context: "128K",
    architecture: "dense",
    category: "general",
    tags: ["tools"],
    benchmarks: {},
    note: "Hermes 8B. Good tool calling in a tiny package.",
  },
  {
    repoId: "01-ai/Yi-34B-Chat",
    name: "Yi 34B",
    hfUrl: "https://huggingface.co/01-ai/Yi-34B-Chat",
    sizeGb: 20,
    paramsTotal: "34B",
    paramsActive: null,
    context: "4K",
    architecture: "dense",
    category: "general",
    tags: [],
    benchmarks: {},
    note: "Yi 34B. Short context (4K). Old but strong for its time.",
  },
  {
    repoId: "upstage/SOLAR-10.7B-Instruct-v1.0",
    name: "Solar:10.7b",
    hfUrl: "https://huggingface.co/upstage/SOLAR-10.7B-Instruct-v1.0",
    sizeGb: 6.5,
    paramsTotal: "11B",
    paramsActive: null,
    context: "4K",
    architecture: "dense",
    category: "general",
    tags: [],
    benchmarks: {},
    note: "Solar 10.7B. Korean. Small context.",
  },
  {
    repoId: "ibm-granite/granite-4.1-30b-instruct",
    name: "Granite4.1:30b",
    hfUrl: "https://huggingface.co/ibm-granite/granite-4.1-30b-instruct",
    sizeGb: 17,
    paramsTotal: "30B",
    paramsActive: null,
    context: "128K",
    architecture: "dense",
    category: "general",
    tags: ["tools"],
    benchmarks: {},
    note: "Enterprise. Apache 2.0. Strong RAG + structured output.",
  },
  {
    repoId: "ibm-granite/granite-4.1-8b-instruct",
    name: "Granite4.1:8b",
    hfUrl: "https://huggingface.co/ibm-granite/granite-4.1-8b-instruct",
    sizeGb: 5,
    paramsTotal: "8B",
    paramsActive: null,
    context: "128K",
    architecture: "dense",
    category: "general",
    tags: ["tools"],
    benchmarks: {},
    note: "Light enterprise model. Apache 2.0. 128K context.",
  },

  //━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  //  REASONING — trained for chain-of-thought / thinking mode
  //━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  {
    repoId: "deepseek-ai/DeepSeek-R1-Distill-Qwen-32B",
    name: "DeepSeek-R1:32b",
    hfUrl: "https://huggingface.co/deepseek-ai/DeepSeek-R1-Distill-Qwen-32B",
    sizeGb: 20,
    paramsTotal: "32B",
    paramsActive: null,
    context: "32K",
    architecture: "dense",
    category: "reasoning",
    tags: ["thinking"],
    benchmarks: {},
    note: "DeepSeek R1 distill. Strong reasoning, 32K context.",
  },
  {
    repoId: "deepseek-ai/DeepSeek-R1-Distill-Qwen-14B",
    name: "DeepSeek-R1:14b",
    hfUrl: "https://huggingface.co/deepseek-ai/DeepSeek-R1-Distill-Qwen-14B",
    sizeGb: 9,
    paramsTotal: "14B",
    paramsActive: null,
    context: "32K",
    architecture: "dense",
    category: "reasoning",
    tags: ["thinking"],
    benchmarks: {},
    note: "R1 distilled to 14B. Light reasoning.",
  },
  {
    repoId: "mistralai/Magistral-24B",
    name: "Magistral:24b",
    hfUrl: "https://huggingface.co/mistralai/Magistral-24B",
    sizeGb: 14,
    paramsTotal: "24B",
    paramsActive: null,
    context: "128K",
    architecture: "dense",
    category: "reasoning",
    tags: ["tools"],
    benchmarks: {},
    note: "Mistral reasoning model. Good for hard analytical problems.",
  },

  //━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  //  REFERENCE — notable models that won't fit consumer hardware
  //━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  {
    repoId: "Qwen/Qwen3-235B-A22B",
    name: "Qwen3:235b",
    hfUrl: "https://huggingface.co/Qwen/Qwen3-235B-A22B",
    sizeGb: 142,
    paramsTotal: "235B",
    paramsActive: "22B",
    context: "256K",
    architecture: "moe",
    category: "general",
    tags: ["tools", "thinking"],
    benchmarks: {},
    note: "Needs 142 GB at Q4. Use API.",
  },
  {
    repoId: "deepseek-ai/DeepSeek-V4-Flash",
    name: "DeepSeek-V4-Flash",
    hfUrl: "https://huggingface.co/deepseek-ai/DeepSeek-V4-Flash",
    sizeGb: 160,
    paramsTotal: "284B",
    paramsActive: "13B",
    context: "1M",
    architecture: "moe",
    category: "coding",
    tags: [],
    benchmarks: {},
    note: "Needs 160 GB at FP4/FP8. Use API.",
  },
  {
    repoId: "deepseek-ai/DeepSeek-V4-Pro",
    name: "DeepSeek-V4-Pro",
    hfUrl: "https://huggingface.co/deepseek-ai/DeepSeek-V4-Pro",
    sizeGb: 290,
    paramsTotal: "1.6T",
    paramsActive: "49B",
    context: "1M",
    architecture: "moe",
    category: "coding",
    tags: [],
    benchmarks: {},
    note: "Needs 290 GB. Cloud only.",
  },
  {
    repoId: "meta-llama/Llama-4-Maverick-127B",
    name: "Llama 4 Maverick",
    hfUrl: "https://huggingface.co/meta-llama/Llama-4-Maverick-127B",
    sizeGb: 80,
    paramsTotal: "127B",
    paramsActive: "17B",
    context: "256K",
    architecture: "moe",
    category: "general",
    tags: ["vision"],
    benchmarks: {},
    note: "Needs 80 GB at Q4. Tight even for 128 GB machines.",
  },
  {
    repoId: "Qwen/Qwen3-Coder-480B",
    name: "Qwen3-Coder:480b",
    hfUrl: "https://huggingface.co/Qwen/Qwen3-Coder-480B",
    sizeGb: 290,
    paramsTotal: "480B",
    paramsActive: null,
    context: "256K",
    architecture: "moe",
    category: "coding",
    tags: [],
    benchmarks: {},
    note: "Needs 290 GB. Cloud only.",
  },
];

export function runnableCandidates(): RegistryEntry[] {
  return REGISTRY.filter((e) => e.sizeGb <= 64);
}